workflows:
  build-android:
    name: Build APK
    instance_type: mac_mini     # ✅ Free-tier instance type
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.sanol.app"
      node: 18
    scripts:
      - name: Install dependencies
        script: npm install
      - name: EAS Login (optional if not logged in)
        script: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "EXPO_TOKEN is not set. Skipping login."
          else
            npx expo login --token $EXPO_TOKEN
          fi
      - name: Build APK with EAS
        script: npx eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
